// Code generated by ent, DO NOT EDIT.

package ent

import (
	"catalog/src/datastore/ent/schema"
	"catalog/src/datastore/ent/system"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	systemFields := schema.System{}.Fields()
	_ = systemFields
	// systemDescType is the schema descriptor for type field.
	systemDescType := systemFields[1].Descriptor()
	// system.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	system.TypeValidator = systemDescType.Validators[0].(func(string) error)
	// systemDescHost is the schema descriptor for host field.
	systemDescHost := systemFields[2].Descriptor()
	// system.HostValidator is a validator for the "host" field. It is called by the builders before save.
	system.HostValidator = systemDescHost.Validators[0].(func(string) error)
	// systemDescCredentials is the schema descriptor for credentials field.
	systemDescCredentials := systemFields[4].Descriptor()
	// system.CredentialsValidator is a validator for the "credentials" field. It is called by the builders before save.
	system.CredentialsValidator = systemDescCredentials.Validators[0].(func(string) error)
	// systemDescCreatedBy is the schema descriptor for created_by field.
	systemDescCreatedBy := systemFields[5].Descriptor()
	// system.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	system.CreatedByValidator = systemDescCreatedBy.Validators[0].(func(string) error)
	// systemDescCreatedAt is the schema descriptor for created_at field.
	systemDescCreatedAt := systemFields[6].Descriptor()
	// system.DefaultCreatedAt holds the default value on creation for the created_at field.
	system.DefaultCreatedAt = systemDescCreatedAt.Default.(func() time.Time)
	// systemDescUpdatedBy is the schema descriptor for updated_by field.
	systemDescUpdatedBy := systemFields[7].Descriptor()
	// system.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	system.UpdatedByValidator = systemDescUpdatedBy.Validators[0].(func(string) error)
	// systemDescUpdatedAt is the schema descriptor for updated_at field.
	systemDescUpdatedAt := systemFields[8].Descriptor()
	// system.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	system.DefaultUpdatedAt = systemDescUpdatedAt.Default.(func() time.Time)
	// system.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	system.UpdateDefaultUpdatedAt = systemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systemDescID is the schema descriptor for id field.
	systemDescID := systemFields[0].Descriptor()
	// system.IDValidator is a validator for the "id" field. It is called by the builders before save.
	system.IDValidator = systemDescID.Validators[0].(func(string) error)
}
