version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: catalog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: catalog_root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: